### ISSUE TITLE
Potentially build with cmake.

### ISSUE THREAD

**Issue by venabled** [conda-forge/proj.4-feedstock#105]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Was wondering your thoughts on building this package with cmake instead of autoconf/tools. The cmake install provides cmake modules for configuration/use in downstream native projects which is super handy.

**Comment by hobu** [comment]
Please provide a PR, I don't think it would be disruptive to start using the cmake build.

**Comment by xylar** [comment]
There was discussion [here](https://github.com/conda-forge/geos-feedstock/pull/60#issuecomment-811503630) that switching to CMake might affect the ABI for GEOS.  I wonder if the same might apply to proj, and we should wait until there is a new release to make the transition.

**Comment by mwtoews** [comment]
PROJ 8.1.0 is planned for July 1st. I could prepare a draft PR here too.

**Comment by mwtoews** [comment]
See draft PR #106 for testing / discussion.
