### ISSUE TITLE
Building PROJ with modern linux

### ISSUE THREAD

**Issue by snowman2** [conda-forge/proj.4-feedstock#112]
Related; https://github.com/pyproj4/pyproj/issues/933

PROJ 8.1 requires `pread64` [ref](https://github.com/pyproj4/pyproj/issues/933#issuecomment-913832744). The current builds for conda-forge don't seem to work.

There are 2 possible reasons:
- conda-forge is building with a version of of linux before `pread64`
- the sqlite package isn't built with the needed  `CFLAGS="-DHAVE_PREAD64 -DHAVE_PWRITE64"` [ref](https://github.com/pyproj4/pyproj/issues/933#issuecomment-913879611)

**Comment by ocefpaf** [comment]
> * conda-forge is building with a version of of linux before `pread64`

I'm not sure. How can we check this? Maybe @isuruf can help but he is very busy at the moment.

**Comment by snowman2** [comment]
@ocefpaf, this build seems to work [ref](https://github.com/conda-forge/sqlite-feedstock/pull/68). One way to check would be to merge that in and build PROJ with this sqlite and see if it works.

**Comment by snowman2** [comment]
Problem resolved with the updated sqlite build:
```
# Name                    Version                   Build  Channel
proj                      8.1.1                h277dcde_0    conda-forge
sqlite                    3.36.0               h9cd32fc_1    conda-forge
```
Apparently the re-build of PROJ wasn't necessary.
