### ISSUE TITLE
unbound variable _CONDA_SET_PROJ_LIB in deactivate.sh

### ISSUE THREAD

**Issue by TormodLandet** [conda-forge/proj.4-feedstock#120]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I am getting the following error on my Azure DevOps Pipeline runs:

```
/usr/share/miniconda/envs/myenv/etc/conda/deactivate.d/proj4-deactivate.sh: line 5: _CONDA_SET_PROJ_LIB: unbound variable
```

The failing command is the conda install command that installs a package that depends on proj
Please use the same :- shell trick as in activate.sh

### Installed packages

```shell
Sorry for my ignorance, is conda-forge an upstream for this package?

  proj               pkgs/main/linux-64::proj-6.2.1-h05a3930_0
```

### Environment info

```shell
Azure Devops with vmImage="ubuntu-18.04"

Running bash CI-step:

conda create -y -n myenv python=3.7 conda-build
source $CONDA/bin/activate activate myenv
conda install -y PACKAGE_THAT_DEPENDS_ON_PROJ_VIA_OTHER_DEPENDENCY  <-- this command fails
```

**Comment by hobu** [comment]
PROJ 6.2.1 is quite old (PROJ 9.0.0 is now the current). It looks like there's an old version on main still. 

There was issues with the activation scripts in the past which should be fixed now. 

I don't think there's a bug for us to fix here though.

**Comment by TormodLandet** [comment]
I saw the version discrepancy, but I also see that if PROJ_LIB is unset in activate.sh then _CONDA_SET_PROJ_LIB is not set

```sh
if [ -n "${PROJ_LIB:-}" ]; then
    export _CONDA_SET_PROJ_LIB=$PROJ_LIB
fi
```

Then, in deactivate.sh this is not checked (should be  "${_CONDA_SET_PROJ_LIB:-}"):

```sh
if [ -n "$_CONDA_SET_PROJ_LIB" ]; then
    export PROJ_LIB=$_CONDA_SET_PROJ_LIB
    unset _CONDA_SET_PROJ_LIB
fi
```

**Comment by hobu** [comment]
oh! Thanks for the report. I thought this was all fixed.
