### ISSUE TITLE
Pin sqlite < 3.40.0 ?

### ISSUE THREAD

**Issue by snowman2** [conda-forge/proj.4-feedstock#127]
Related: https://github.com/pyproj4/pyproj/issues/1192

Any issues pinning sqlite?

**Comment by ocefpaf** [comment]
It may prevent the installation of proj with newer packages compiled with newer sqlite but, if this is an upstream limitation, there is nothing we can do. I'd just add a link to the upstream issue so we can follow up and unpin when this is fixed.

**Comment by snowman2** [comment]
Seems SQLite may not be the root cause.
