### ISSUE TITLE
Having trouble with libproj.so

### ISSUE THREAD

**Issue by phobson** [conda-forge/proj.4-feedstock#13]
Noticed this in a TravisCI build of a module that uses `rasterio`

Build log here:
https://travis-ci.org/Geosyntec/gisutils/jobs/165940148#L684

```
$ python check_gisutils.py ${ARGS}
Traceback (most recent call last):
  File "check_gisutils.py", line 5, in <module>
    import gisutils
  File "/home/travis/build/Geosyntec/gisutils/gisutils/__init__.py", line 1, in <module>
    from . import raster
  File "/home/travis/build/Geosyntec/gisutils/gisutils/raster.py", line 3, in <module>
    import rasterio
  File "/home/travis/miniconda/envs/test/lib/python3.4/site-packages/rasterio/__init__.py", line 15, in <module>
    from rasterio._base import (
ImportError: libproj.so.9: cannot open shared object file: No such file or directory
```

I see this in a completely fresh environment locally with fiona:

```
conda create --name=proj python=3.4 fiona --channel=conda-forge --yes
source activate proj
python -c "import fiona"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/paul/miniconda/envs/proj/lib/python3.4/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/home/paul/miniconda/envs/proj/lib/python3.4/site-packages/fiona/collection.py", line 7, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libproj.so.9: cannot open shared object file: No such file or directory
(proj) paul@POR-PHOBSON10:/mnt/c/Users/phobson$
```

I cant reproduce on windows due to  https://github.com/conda-forge/hdf5-feedstock/issues/41

**Comment by ocefpaf** [comment]
@phobson I updated `proj.4` from `4.9.2` to `4.9.3`. Patch releases should not break the ABI but....

I am pinning `proj.4` down to a patch level now and this problem should go away soon. I will be some time until I re-build everything, specially `gdal`.

**Comment by ocefpaf** [comment]
@phobson can you re-start that CI and check if the error is gone?

**Comment by ocefpaf** [comment]
Closing this. Let me know if you are still suffering with this issue.

**Comment by phobson** [comment]
Oh dang. Sorry. This has been cleared up on at least the Windows build.
Thanks!

**Comment by mikeskaug** [comment]
I have a build that now breaks when importing fiona. This is part of the output from CI:
```
  File "/opt/miniconda/conda-bld/recipe_1479145503435/work/flightlines2geometry/test/test_write_shapefile.py", line 4, in <module>
    import fiona
  File "/opt/miniconda/conda-bld/recipe_1479145503435/_b_env_placehold_placehold_placeho/lib/python3.5/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/opt/miniconda/conda-bld/recipe_1479145503435/_b_env_placehold_placehold_placeho/lib/python3.5/site-packages/fiona/collection.py", line 7, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libproj.so.9: cannot open shared object file: No such file or directory

```

The last successful build was 3 days ago.

**Comment by michaelbroe** [comment]
I may be having a similar problem on Ubuntu. In `R:`

```
> library(rgdal)
Loading required package: sp
Error: package or namespace load failed for ‘rgdal’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/scr/broe.1/miniconda3/envs/r-spat/lib/R/library/rgdal/libs/rgdal.so':
  libproj.so.13: cannot open shared object file: No such file or directory
```
Conda listings:

```
# Name                    Version                   Build  Channel
proj4                     4.9.3                h470a237_8    conda-forge
r-rprojroot               1.3_2           r351h6115d3f_1001    conda-forge
gdal                      2.3.2            py36hb00a9d7_0    conda-forge
libgdal                   2.3.2                hc73897a_0    conda-forge
r-rgdal                   1.3_6            r351h285a78d_1    conda-forge
```
Listing of conda-env lib directory:

```
$ ls -1 <conda-env>/lib/libproj.*
libproj.a
libproj.so
libproj.so.12
libproj.so.12.0.0
```
And:

```
$ ls <conda-env>/lib/R/library/rgdal/libs
rgdal.so
```

Any help appreciated!

**Comment by jeverling** [comment]
I think you could install `libproj13` as a temporary workaround (note the apt-config is for Debian, you should probably adjust accordingly for Ubuntu):

`echo "APT::Default-Release "stable";" >> /etc/apt/apt.conf.d/99defaultrelease`
`echo -e "deb     http://ftp.de.debian.org/debian/    testing main contrib non-free\ndeb-src http://ftp.de.debian.org/debian/    testing main contrib non-free\n\ndeb     http://security.debian.org/         testing/updates  main contrib non-free" >> /etc/apt/sources.list.d/testing.list`
`apt-get update && apt-get -t testing install libproj13`

**Comment by darribas** [comment]
I'm not sure this fits into this issue, but it's the only place where I've found related help. How would you install `libproj13` in Ubuntu Bionic? Anybody has any suggestion? Thank you very much in advance.

**Comment by jeverling** [comment]
Hey darribas, I think the process will almost be the same, just with different release name and sources.lists. The package is available in the *universe* repos for `cosmic`.
I have weak network so I can't test, otherwise I would try in a Ubuntu Docker container.
Here is what I think _should_ work, but no guarantees:

`echo "APT::Default-Release "bionic";" >> /etc/apt/apt.conf.d/99defaultrelease`

`echo -e "deb http://be.archive.ubuntu.com/ubuntu/ cosmic main universe\ndeb-src http://be.archive.ubuntu.com/ubuntu/ cosmic main universe" >> /etc/apt/sources.list.d/cosmic.list`

`apt-get update && apt-get -t cosmic install libproj13`

Let me know how it goes.

**Comment by jeverling** [comment]
A word of warning: this is a temporary workaround and it might be a bad idea to just install a library from a totally different version, things might break.
My objective was just to get rasterio to work inside a Docker container, so I didn't care. But it sounds like you might be trying this on your Desktop, so be aware that other things that depend on `libproj` might break  when you upgrade to the version from `cosmic`.

**Comment by jeverling** [comment]
If you run `apt-cache rdepends libproj12`, you will see what packages depend on this package. So if you are using any of those packages they might be affected by the update.
OK I'm going to shut up now this is really getting out of scope of this issue. :)
