### ISSUE TITLE
Why we are skipping `ppc64le`

### ISSUE THREAD

**Issue by xylar** [conda-forge/proj.4-feedstock#148]
We have been forced to skip `ppc64le` on this feedstock, resulting on any downstream feedstocks that depend on `proj` having to do the same.  This is the story of why.

We had silenced an error for ppc64le in https://github.com/conda-forge/proj.4-feedstock/pull/141. This led to downstream problems. I attempted to debug this issue in https://github.com/conda-forge/proj.4-feedstock/pull/142 without success, so we disabled ppc64le support in https://github.com/conda-forge/proj.4-feedstock/pull/143 (but neglected to remove the code that skipped one of the tests for ppc64le). I have unsilenced the test in #142 and again in #147. In both cases, the test produces different results the first and second time it is run on ppc64le. None of the maintainers here want to sink any more time into it.

**Comment by mwtoews** [comment]
If you want to side-step the ppc64le error, apply a69c9b68ff6936ddcf16e2acc673bff6e25d01c7 which fetches a grid resource needed for the test.

**Comment by xylar** [comment]
@mwtoews, do you think the problem is just with `ppc64le` emulation?  If so, did you feel like you basically had a fix in #142 that we could also use downstream? The reason we went with skipping `ppc64le` was that the error cropped up again in `pyproj`: 
https://github.com/conda-forge/pyproj-feedstock/pull/148#issuecomment-2017587784
If it's just a question of adding the same fix both here and on `pyproj`, maybe that's an easy enough solution that lets us use ppc64le again.  

I think the hesitancy maybe have been that we don't know if the downloading is working correctly in ppc64le "in the wild".  Did you do tests to know whether we see this problem in the wild or not?  And have we had any reports of it?  Maybe there are just not enough ppc64le users to know one way or the other.

**Comment by mwtoews** [comment]
We never really got to the root cause of the issue, except that I was able to locally reproduce it with via emulation with qemu and docker, and only with a coda-forge compiler stack. I don't have access to PPC64 hardware, and ppc64le users haven't chimed in. Considering all the other tests are OK, I think it's fine to provide this package to the handful of potential users. Pyproj could also somehow use the same workaround to ensure the grid is locally available before testing:

    projsync --file us_noaa_nadcon5_nad27_nad83_1986_conus.tif

**Comment by xylar** [comment]
Okay, maybe I can find time to give that a go this coming weekend.  I should be able to test with the "broken" package we already have for ppc64le here to see if things work on `pyproj` before coming back here.
