### ISSUE TITLE
cs2cs epsg file lookup error

### ISSUE THREAD

**Issue by megies** [conda-forge/proj.4-feedstock#18]
I hope this is the right place for this bug report..

The `cs2cs` binary shipped with the proj package has a path lookup problem:

```
$ which cs2cs
/home/megies/anaconda/bin/cs2cs
$ PROJ_DEBUG=3 cs2cs +init=epsg:4326 +to +init=epsg:2975 
pj_open_lib(epsg): call fopen(/opt/conda/envs/_build/share/proj/epsg) - failed

Using from definition: init=epsg:4326 
Rel. 4.9.2, 08 September 2015
<cs2cs>: 
projection initialization failure
cause: no system list, errno: 2

program abnormally terminated
```

It is trying to lookup the epsg file under some temporary build-time path, it seems, while it should be looking it up under the environments `share/proj` directory. Forcing the correct path makes it work:

```
$ export PROJ_LIB=$(dirname $(dirname $(which proj)))/share/proj
$ PROJ_DEBUG=3 cs2cs +init=epsg:4326 +to +init=epsg:2975 
pj_open_lib(epsg): call fopen(/home/megies/anaconda/share/proj/epsg) - succeeded

pj_open_lib(epsg): call fopen(/home/megies/anaconda/share/proj/epsg) - succeeded
```

To fix this problem, the installed `proj` binary should lookup the correct path relative to it's own directory, I think.

**Comment by ocefpaf** [comment]
> I hope this is the right place for this bug report..

It is :smile:

> To fix this problem, the installed proj binary should lookup the correct path relative to it's own directory, I think.

Indeed. I think I know how to fix this. Let me try something...

**Comment by ocefpaf** [comment]
@megies the new binaries are in the channel. Can you test it again and let me know if that works for you?

**Comment by megies** [comment]
@ocefpaf, works! Thumbs up for the fix! :+1: 


off-topic side note: conda didn't want to upgrade automatically for me, I had to explicitly use the newer version on CL (seems it was preferring the older version from the higher-priority `defaults` channel?)

```
$ conda search proj4
Fetching package metadata ...........
proj4                     .  4.9.1                         0  defaults        
                          *  4.9.2                         0  defaults        
                             4.9.3                         0  conda-forge     
                          .  4.9.3                         1  conda-forge     
$ conda upgrade proj4
Fetching package metadata ...........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /home/megies/anaconda:
#
proj4                     4.9.2                         0  
$ cat .condarc
channels:
  - defaults
  - conda-forge
  - obspy
$ conda install proj4=4.9.3
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment /home/megies/anaconda:

The following packages will be UPDATED:

    proj4: 4.9.2-0 --> 4.9.3-1 conda-forge

Proceed ([y]/n)? 

Unlinking packages ...
[      COMPLETE      ]|#####################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#####################################################################################################| 100%
```

off-topic side note no. 2: I understand `proj.4` is an old deprecated naming of the package..? I had one of those lingering around in addition to the `proj4` package and just manually uninstalled them. Is there some construct like `Conflicts: ...` or `Replaces: ...` (debian apt lingo) in `conda` to tell `conda` to uninstall those packages when `proj4` is installed/updated?

**Comment by ocefpaf** [comment]
> seems it was preferring the older version from the higher-priority defaults channel?

That is the expected behavior. It is pretty safe to put `conda-forge` on top of `defaults` though.

> off-topic side note no. 2: I understand proj.4 is an old deprecated naming of the package..? I had one of those lingering around in addition to the proj4 package and just manually uninstalled them. Is there some construct like Conflicts: ... or Replaces: ... (debian apt lingo) in conda to tell conda to uninstall those packages when proj4 is installed/updated?

No. But we all would love that! I believe there are some issues opened in conda/conda-build already about that.

**Comment by megies** [comment]
> It is pretty safe to put conda-forge on top of defaults though.

The downside is that newer package from the `defaults` channel get overriden in this case.. :-/

```
The following packages will be SUPERCEDED by a higher-priority channel:

    conda:        4.2.12-py27_0           --> 4.1.12-py27_0         conda-forge
```

**Comment by ocefpaf** [comment]
I agree. But that will only happen with `conda` and `conda-*` packages. IMO those should not be on `conda-forge` because those are the only packages guarantee to be more up-to-date in `defaults`.

Maybe, one day when continuum folks adopt conda-forge as a "testing bed" for their packages, that won't be true :smile:
