### ISSUE TITLE
This version vs defaults

### ISSUE THREAD

**Issue by pelson** [conda-forge/proj.4-feedstock#2]
@ocefpaf - would you mind highlighting how this recipe is an improvement on the distribution available on defaults? 

It seems that https://github.com/conda-forge/staged-recipes/pull/138 is suffering from not having the distribution from here, so there must be _something_ different...

**Comment by ocefpaf** [comment]
We don't have the recipe for the default channel. That makes it hard to compare the builds. I will see if I can come up with something. (symbols, conda inspect, etc.)

**Comment by ocefpaf** [comment]
Don't really know any tool to inspect Windows `.lib`/`.dll` files :cry:

Here are the differences I found:
- conda-forge's proj.4 `.exe` and `dll` are in the `Library\bin` directory. The default channel's are at the root of the tarball directory.
- conda-forge's `proj.lib`, when compiled with VC10 (PY34), is 1.6 MB while the default channel's is always < 1 MB

Conda-forge's `blt.bat` is very simple:

``` bat
nmake /f makefile.vc

nmake INSTDIR=%LIBRARY_PREFIX% /f makefile.vc install-all
if errorlevel 1 exit 1

move %LIBRARY_PREFIX%\bin\*.* %PREFIX%
if errorlevel 1 exit 1
```

**Comment by ocefpaf** [comment]
For future reference here is the Appeyor failure we got when using the default channel `proj.4` and Cartopy for Python 3.4.

``` shell
proj.lib(PJ_bipc.obj) : error LNK2001: unresolved external symbol __imp_hypot
proj.lib(PJ_aeqd.obj) : error LNK2019: unresolved external symbol __imp_hypot referenced in function e_forward
proj.lib(PJ_geos.obj) : error LNK2001: unresolved external symbol __imp_hypot
proj.lib(proj_etmerc.obj) : error LNK2001: unresolved external symbol __imp_hypot
proj.lib(PJ_eqdc.obj) : error LNK2001: unresolved external symbol __imp_hypot
proj.lib(PJ_bonne.obj) : error LNK2001: unresolved external symbol __imp_hypot
proj.lib(PJ_aea.obj) : error LNK2001: unresolved external symbol __imp_hypot
proj.lib(PJ_lcc.obj) : error LNK2001: unresolved external symbol __imp_hypot
proj.lib(PJ_laea.obj) : error LNK2001: unresolved external symbol __imp_hypot
proj.lib(PJ_gnom.obj) : error LNK2001: unresolved external symbol __imp_hypot
proj.lib(PJ_sterea.obj) : error LNK2001: unresolved external symbol __imp_hypot
proj.lib(PJ_ortho.obj) : error LNK2001: unresolved external symbol __imp_hypot
proj.lib(PJ_oea.obj) : error LNK2001: unresolved external symbol __imp_hypot
proj.lib(PJ_mod_ster.obj) : error LNK2001: unresolved external symbol __imp_hypot
proj.lib(PJ_sconics.obj) : error LNK2001: unresolved external symbol __imp_hypot
proj.lib(PJ_stere.obj) : error LNK2001: unresolved external symbol __imp_hypot
proj.lib(PJ_nsper.obj) : error LNK2001: unresolved external symbol __imp_hypot
proj.lib(PJ_tpeqd.obj) : error LNK2001: unresolved external symbol __imp_hypot
build\lib.win-amd64-3.4\cartopy\_crs.pyd : fatal error LNK1120: 1 unresolved externals
error: command 'c:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\Bin\\amd64\\link.exe' failed with exit status 1120
```

**Comment by pelson** [comment]
For reference: https://github.com/SciTools/conda-recipes-scitools/issues/94

**Comment by ocefpaf** [comment]
> For reference: SciTools/conda-recipes-scitools#94

Forgot about that.

@msarahan Can you send this upstream (the default channel `Proj.4`)?

**Comment by pelson** [comment]
> Forgot about that.

Me too, and I created it. I have a memory like a :fish: :wink:

**Comment by msarahan** [comment]
@groutr - can you take this on (moving back into Anaconda?)

Just so you guys know, we are having issues getting recipes back in to defaults.  We are getting pushback on the use of jinja2, which is/was not used at all in the internal recipes.  We may resort to copying content of recipes until we can get that figured out.

**Comment by pelson** [comment]
> We are getting pushback on the use of jinja2, which is/was not used at all in the internal recipes. We may resort to copying content of recipes until we can get that figured out.

Of course, you could just expand the jinja using conda and copy the expanded form, but that is a peculiar thing to do if you ask me.

I'm struggling to see any benefits from **not** using jinja2 - it allows you to template stuff that is useful to template, and not template stuff that isn't (e.g. the version string). @msarahan - sorry you are in that situation - I imagine it isn't an easy thing to stomach.

**Comment by ocefpaf** [comment]
I believe we can close this. Please re-open if I am wrong.
