### ISSUE TITLE
Optional shift files?

### ISSUE THREAD

**Issue by hobu** [conda-forge/proj.4-feedstock#37]
Should we have an optional package for the grid shift files? See the "datumgrid" files at https://proj4.org/download.html#current-release  These are quite useful and often needed, but users don't always know to fetch them. Some packages could optionally chose to depend on them, but they are quite large, and it would only take a package like GDAL or PDAL using them to functionally make them required anyway. 

What should we do?

**Comment by kbevers** [comment]
The intention with the regional grid packages was that package systems could include them as optional packages, allowing users to install only the grids they need.

With that in mind I would encourage the addition of packages for `proj-datumgrid-europe`, `proj-datumgrid-north-america` and `proj-datumgrid-oceania`. Of course those should all be dependent on the `proj4` package. If that is technically possible I dont know. It seems that the existing `proj4` package installs the grids in a folder only that package knows about. This can be overcome with PROJ 6 that allow multiple grid folders to be specified in `PROJ_LIB`.

**Comment by hobu** [comment]
> allowing users to install only the grids they need.

The problem is you don't know you need them until you need them, and the software doesn't tell you when you need them or where to get them.

**Comment by kbevers** [comment]
> The problem is you don't know you need them until you need them, and the software doesn't tell you when you need them or where to get them.

Well, that can be changed - a fun little project for Hobu Inc? :)

Seriously though, if you live in one of the three regions, chances are you will need to install the corresponding grid package.

**Comment by hobu** [comment]
> Well, that can be changed - a fun little project for Hobu Inc? :)

Ha! No one pays for such things. 

Does PROJ emit a message now when it tries to apply a shift when no grid file(s) is available? It didn't used to do that in the past unless you had a bunch of debug noise turned up.

**Comment by kbevers** [comment]
> Ha! No one pays for such things.

Then it probably can't be changed...

> Does PROJ emit a message now when it tries to apply a shift when no grid file(s) is available? It didn't used to do that in the past unless you had a bunch of debug noise turned up.

It returns a suitable error code when it can't find any non-optional grids specified in a projstring (like `+nadgrids=grid1,grid2`). Problem is that everyone always adds (including PROJ itself) `@null` at the end of grid lists which ensures no errors are thrown and no grid corrections are applied. So that's not very helpful. I don't know if the new ISO19111 code is more helpful in this regard.

**Comment by hobu** [comment]
Our PROJ back-and-forth aside, what does Conda Forge want to do in regards to shift files?

**Comment by ocefpaf** [comment]
> Our PROJ back-and-forth aside, what does Conda Forge want to do in regards to shift files?

I believe that multiple packages for each grid is the best way to solve this. At the moment we are bundling only http://download.osgeo.org/proj/proj-datumgrid-1.7.zip. Note that we can probably achieve that in the same feedstock using multiple outputs.

**Comment by ocefpaf** [comment]
We have packages for `proj-datumgrid-europe`, `proj-datumgrid-north-america`, `proj-datumgrid-oceania`, and `proj-datumgrid-world` now.
