### ISSUE TITLE
activate/deactivate do not support csh and variants

### ISSUE THREAD

**Issue by xylar** [conda-forge/proj.4-feedstock#43]
Issue: When activating a conda environment in csh (or tcsh or other variants) with `source <path>/profile.d/conda.csh`, the environment variables for this shell are not set, causing any packages that depend on `PROJ_LIB`  (e.g. basemap) to fail to import.

I'm happy to provide more details about the conda environment, etc. if they are relevant but i think the problem is fairly simply that there are only scripts for `sh` and not `csh` here:
https://github.com/conda-forge/proj.4-feedstock/tree/master/recipe/scripts

and added here:
https://github.com/conda-forge/proj.4-feedstock/blob/master/recipe/build.sh#L18-L19

Presumably a corresponding set of `.csh` scripts would take care of this issue?

**Comment by xylar** [comment]
@ocefpaf, if you agree that adding `.csh` scripts would take care of this issue, I'm happy to figure this out and make a PR.  I've had a bunch of users of the environments I set up for our project who don't understand why things don't work in `csh` and it would be great to get this worked out.

**Comment by ocefpaf** [comment]
Sure. Go for it! Here is an example that may be helpful: https://github.com/conda-forge/pythia8-feedstock/pull/3/files
