### ISSUE TITLE
EPSG codes no longer work on Windows

### ISSUE THREAD

**Issue by djhoese** [conda-forge/proj.4-feedstock#56]
Issue: I'm currently helping debug some stuff with [ci-helpers](https://github.com/astropy/ci-helpers) and I finally got a Windows environment on travis to run my unit tests for pyresample. However, there are some tests failing that weren't failing on linux/osx earlier this morning (rerunning them now). I'm trying to track down what may have changed and hoping the people who deal with this feedstock will be the quickest solution. @snowman2 and @ocefpaf seems you've been dealing with the newer versions of PROJ, but this environment is still using the older 5.4.0. Here's what is installed:

```
    proj4-5.2.0                |    h6538335_1004         3.4 MB  conda-forge
    pyproj-1.9.6               |py36hfa6e2cd_1002         237 KB  conda-forge
```

When I do `Proj("+init=EPSG:6932")` with pyproj I get:

```
  File "c:\users\travis\build\pytroll\pyresample\pyresample\geometry.py", line 1041, in __init__
    proj = Proj(projection)
  File "C:\tools\miniconda3\envs\test\lib\site-packages\pyproj\__init__.py", line 362, in __new__
    return _proj.Proj.__new__(self, projstring)
  File "_proj.pyx", line 129, in _proj.Proj.__cinit__
RuntimeError: b'no arguments in initialization list'
```

My guess is that either PROJ or this feedstock changed the default to no longer the `+init` syntax (since I know it is being deprecated), but I'm having trouble tracking down where that happened. Any ideas?

**Comment by snowman2** [comment]
Ref: https://github.com/pyproj4/pyproj/issues/134

**Comment by djhoese** [comment]
Thanks! Ok so I can't update to pyproj 2.1.* yet because of other dependencies (cartopy I think). Seeing as this only fails on the Windows environment, my guess is that we are either not activating the environment properly on Windows or there is a bug in conda not re-activating things after installing. I'll see what I can figure out.

**Comment by djhoese** [comment]
Judging by the failing Windows job: https://travis-ci.org/pytroll/pyresample/jobs/571407230#L2054

And the successful linux job: https://travis-ci.org/pytroll/pyresample/jobs/571407228#L3773

I don't think the proj deactivate/activate scripts are being executed for Windows bash. This may be a conda bug.

**Comment by djhoese** [comment]
No, this is a build issue. This tarball https://anaconda.org/conda-forge/proj4/5.2.0/download/win-64/proj4-5.2.0-h6538335_1004.tar.bz2 is the currently preferred win64 tarball and includes `info/recipe/scripts/activate.sh` scripts, but not the `etc/conda/activate.d/proj4-activate.sh` scripts.

However, the build just before that is this tarball https://anaconda.org/conda-forge/proj4/5.2.0/download/win-64/proj4-5.2.0-hc56fc5f_1004.tar.bz2 and it includes the info and the etc scripts.

@ocefpaf Any idea why there were two tarballs for win-64 in the last 5.2 build?

**Comment by xylar** [comment]
@ocefpaf, it seems like two CIs are both uploading tarballs, since they're happening at the same time.  Is this part of what you fixed with your last PR (#55)?  Assuming so, I'm going to follow 8c791114ca2df99d813eebe4291eef2213630172 but for the 5.2.0 branch.

**Comment by xylar** [comment]
@djhoese, thanks for the detective work on this.  I realize it's not the version that you need, but could you see if the correct activation scripts are in https://anaconda.org/conda-forge/proj/6.1.1/download/win-64/proj-6.1.1-ha7a8c7b_0.tar.bz2 ? It looked to me like they were there.  

If so, this would suggest that the version being built in #57 will also have the scripts, as expected and the appveyor version was the one not correctly including those scripts.

**Comment by djhoese** [comment]
@xylar 

```
$ tar -tzf proj-6.1.1-ha7a8c7b_0.tar.bz2 | grep "activate.sh"
info/recipe/scripts/deactivate.sh
info/recipe/scripts/activate.sh
```

So it does *not* have the activation scripts (they should appear in `info` and in `etc/conda`.

**Comment by xylar** [comment]
@djhoese I don't think you're grepping for the right file.  Windows gets activate via a .bat file:
```
tar tvf proj-6.1.1-ha7a8c7b_0.tar.bz2 | grep "activate.bat"
-rwxrwxrwx 0/0             181 2019-08-14 07:57 etc/conda/deactivate.d/proj4-deactivate.bat
-rwxrwxrwx 0/0             181 2019-08-14 07:57 info/recipe/scripts/deactivate.bat
-rwxrwxrwx 0/0             229 2019-08-14 07:57 info/recipe/scripts/activate.bat
-rwxrwxrwx 0/0             229 2019-08-14 07:57 etc/conda/activate.d/proj4-activate.bat
```
I don't think the .sh files are expected to be there for the Windows install.

**Comment by xylar** [comment]
The same appears to be the case for both of the previous files:
```
$ tar -tvf proj4-5.2.0-hc56fc5f_1004.tar.bz2 | grep "etc/conda/"
-rwxrwxrwx 0/0             174 2019-07-19 11:37 etc/conda/deactivate.d/proj4-deactivate.bat
-rwxrwxrwx 0/0             217 2019-07-19 11:37 etc/conda/activate.d/proj4-activate.bat

$ tar -tvf proj4-5.2.0-h6538335_1004.tar.bz2 | grep "etc/conda/"
-rwxrwxrwx 0/0             174 2019-07-19 11:37 etc/conda/deactivate.d/proj4-deactivate.bat
-rwxrwxrwx 0/0             217 2019-07-19 11:37 etc/conda/activate.d/proj4-activate.bat
```
So at this point, I don't see why one would work and the other not.

**Comment by xylar** [comment]
@djhoese It seems like you're expecting the shell activation scripts also to be available in Windows.  They would be easy enough to add but I've not seen that done in other conda-forge recipes.  The conda documentaiton also seems to suggest that the `.bat` files are the expected way to activate/deactivate:

https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#windows

**Comment by xylar** [comment]
Ah, I found this:
https://github.com/conda-forge/gdal-feedstock/blob/master/recipe/install_lib.bat#L25-L30

So gdal is copying both sets of activation scripts.  We can do the same.

**Comment by ocefpaf** [comment]
@xylar thanks for debugging this and sorry for the late response. (I'm "out of office" for the next 15 days.)

indeed the right fix for people using shell-like terminals on Windows is to copy both activation scripts.

**Comment by ocefpaf** [comment]
#57 and #58 should fix this.

**Comment by djhoese** [comment]
@xylar As I think you've realized, you can run more than just cmd.exe on Windows now including a full bash environment. Conda detects or is told to initial bash and uses the .sh scripts for activation.

**Comment by djhoese** [comment]
Also (now that I'm fully awake), thank you for fixing this and helping me along the way.
