### ISSUE TITLE
PROJ_LIB not set in Windows bash or powershell

### ISSUE THREAD

**Issue by djhoese** [conda-forge/proj.4-feedstock#59]
I noticed some strange behavior with pyproj 1.9.6 using PROJ 5.2.0 on Windows and tracked it down to a problem with the activate scripts for bash and powershell (if meant to be supported). This doesn't seem to be a problem for newer versions of PROJ (greater than 5.2.0), but since not all of my dependencies were with newer versions of PROJ I'm a little stuck. I'm guessing PROJ >5.2 does a better job finding the PROJ directory? Or maybe there is a patch in the build to point it to the right place?

A simple python example:

```
conda create -y -n test python=3.7 pyproj rasterio cartopy gdal
conda activate test
from pyproj import Proj; pj = Proj({'proj': 'eqc', 'lon_0': 0.0, 'lat_0': 0.0})"
```

This will produce:

```
(test) PS C:\Users\User> python -c "from pyproj import Proj; pj = Proj({'proj': 'eqc', 'lon_0': 0.0, 'lat_0': 0.0})"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\User\Miniconda3\envs\test\lib\site-packages\pyproj\__init__.py", line 362, in __new__
    return _proj.Proj.__new__(self, projstring)
  File "_proj.pyx", line 129, in _proj.Proj.__cinit__
RuntimeError: b'major axis or radius = 0 or not given'
```

If you then set PROJ_LIB, it works fine. Powershell example:

```
Set-Item Env:PROJ_LIB "C:\Users\User\Miniconda3\envs\test\Library\share"
```

This is also happening for me on Travis CI for one of my projects where travis defaults to using git bash for Windows execution. I think the easiest fix may be to change the last `elif` of the `activate.sh` to an `else` [here](https://github.com/conda-forge/proj.4-feedstock/blob/master/recipe/scripts/activate.sh#L13) but it would have to be backported to PROJ 5.2.0 to fix the issue I'm seeing.

I'm not an expert on PROJ or Windows so let me know what doesn't make sense and what is unreasonable.

<br/>
Environment (<code>conda list proj</code>):
<details>

```
$ conda list proj
# packages in environment at C:\Users\User\Miniconda3\envs\test:
#
# Name                    Version                   Build  Channel
proj4                     5.2.0             h6538335_1005    conda-forge
pyproj                    1.9.6           py37hfa6e2cd_1002    conda-forge
```
</details>

**Comment by xylar** [comment]
@djhoese, I don't think changing that `elif` to an `else` would solve the problem you're seeing.  If that directory doesn't exist, there must be some other problem with the installation.

It seems like you're having to set `PROJ_LIB` to point to `Library\share`, not `Library\share\proj`, which suggests that data isn't ending up in the right place during the install.  Can you verify that?

**Comment by xylar** [comment]
It seems possible that the equivalent of these steps for the current version:
https://github.com/conda-forge/proj.4-feedstock/blob/master/recipe/bld.bat#L24-L26
are missing from 5.2.0:
https://github.com/conda-forge/proj.4-feedstock/blob/v5.2.0/recipe/bld.bat

@ocefpaf, do you have any thoughts on this?  I am also really inexpert on Windows so I'm just doing my best to figure out what relevant differences there might be between the old and new build.

**Comment by xylar** [comment]
Looking at the documentaiton for PROJ 5.2.0 under the windows install:
https://github.com/OSGeo/PROJ/blob/5.2.0/README.md
I see:
> On Windows you have to set the `PROJ_LIB` environment variable to make sure that PROJ can find the resource files that it needs. For the default install directory you can set `PROJ_LIB` with:
> ```
> C:\> set PROJ_LIB=C:\PROJ\share
>```

So it does look like we're pointing to the wrong place during activation.  Indeed, we don't point to a `proj` subdirectory in `activate.bat`.

I'll fix this and do new build.  Thanks for pointing out this problem, @djhoese!

**Comment by xylar** [comment]
Should be addressed by #60

**Comment by djhoese** [comment]
@xylar Does the master branch also need to be updated (drop the `/proj`)?

**Comment by xylar** [comment]
No, I don't think so.  files should be getting put in a `proj` subdirectory (as they should be!):
https://github.com/conda-forge/proj.4-feedstock/blob/master/recipe/bld.bat#L24-L26

**Comment by xylar** [comment]
That's presumably why newer versions weren't giving you trouble.

**Comment by djhoese** [comment]
I no longer get the original error with the new build. Now my tests fail for a completely expected reason 😉 Thanks!
