### ISSUE TITLE
Relax PROJ pin?

### ISSUE THREAD

**Issue by hobu** [conda-forge/proj.4-feedstock#64]
PROJ is following a normal semver versioning scheme, but its pin in recipe.yml is 

`{{ pin_subpackage('proj', max_pin='x.x.x') }}` 

which prevents packages like libgdal from picking up the latest PROJ. Could this be relaxed to x.x?

**Comment by ocefpaf** [comment]
Before proj 6 this would not be possible but I guess we should do it now that the releases are stable and frequent. However, the ability lab report does not look good: https://abi-laboratory.pro/?view=timeline&l=proj

**Comment by hobu** [comment]
That indeed looks messy. Can we instead have a policy that rerenders GDAL if a PROJ release happens? PROJ 6.x is now a hard dependency of GDAL 3.x going forward. They should be moving together, and we're trying to sync releases to make that convenient.

**Comment by ocefpaf** [comment]
They already are. The run_exports here and conda-forge's global pin ensures it. If you are facing any packages issues please let me know b/c that may mean we did something wrong.

**Comment by hobu** [comment]
I'm trying to rerender PDAL to catch up, and when it pulls GDAL, I get PROJ 6.2.0 instead of 6.2.1

**Comment by ocefpaf** [comment]
That is correct with our pinning, we can bump it here https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/50052c574f907a0c903f18fcb3d1bcf507ac30d4/recipe/conda_build_config.yaml#L557, and run a migrator to get everything on the latest proj.

**Comment by hobu** [comment]
There were some [significant fixes in 6.2.1](https://github.com/OSGeo/PROJ/releases/tag/6.2.1) that we need for PDAL and GDAL.

**Comment by ocefpaf** [comment]
I'll put up a migrator first thing tomorrow morning. (On mobile only now.)

**Comment by hobu** [comment]
I tried rerendering both PDAL and GDAL, but it is still grabbing 6.2.0 instead of 6.2.1. Is there something else that needs to be rerendered?

**Comment by xylar** [comment]
Did you try the following?
```
conda update conda-smithy conda-forge-pinning
conda smithy rerender
```
It worked fine for me.  I just made a PR for gdal: https://github.com/conda-forge/gdal-feedstock/pull/347

**Comment by xylar** [comment]
If you're doing a local build, you may need to do:
```
conda build -m .ci_support/linux_.yaml recipe/
```
or similar to make sure you pull in the pinnings that conda-forge CI will be using.  If you do a straight-up conda build without the pinnings, it should still pull in the latest version, though, so I don't know why that wasn't working for you.  Maybe provide a little more detail?

**Comment by xylar** [comment]
Should be addressed by https://github.com/conda-forge/gdal-feedstock/pull/347

**Comment by ocefpaf** [comment]
Thanks to @xylar, who covered for the bot's absence due to maintenance, we have pretty much completed all the crucial packages. @hobu you should be able to re-render and rebuild pdal now.
