### ISSUE TITLE
Make activate.sh posix compliant

### ISSUE THREAD

**Issue by nlgranger** [conda-forge/proj.4-feedstock#67]
I think [recipe/scripts/activate.sh](https://github.com/conda-forge/proj.4-feedstock/blob/master/recipe/scripts/activate.sh) is being source and not executed by conda scripts, so the `#!/bin/bash` is ignored.
If conda is run from /bin/sh as it is the case in CI environments or docker builds, then bash syntax extensions cause issues.

Coud you please use the standard test syntax `if [ -n "$PROJ_LIB" ]; then` instead of `if [[ -n "$PROJ_LIB" ]]; then`?

**Comment by ocefpaf** [comment]
> Coud you please use the standard test syntax `if [ -n "$PROJ_LIB" ]; then` instead of `if [[ -n "$PROJ_LIB" ]]; then`?

I'm not an expert to say what is standard or not but I'd merge a PR adding that if you want to open one.
