### ISSUE TITLE
PROJ 7.0.0-1 - latest build failed to build on Windows

### ISSUE THREAD

**Issue by djhoese** [conda-forge/proj.4-feedstock#75]
The latest PROJ build failed on master for Windows. Could someone restart it?

**Comment by xylar** [comment]
I reran but, strangely, `conda.exe` could not be found.  I wonder if there's something wrong with the setup?  I'll look into it.

**Comment by xylar** [comment]
Looks like we need to rerender:
https://gitter.im/conda-forge/conda-forge.github.io?at=5e6a5c2995b8ff0bbfafb14c

**Comment by xylar** [comment]
@djhoese, nice catch.  We seem to have been caught in the unlucky spot of having something change under us between testing of the PR and CI running on the merge.  Hopefully, it's fixed now.

**Comment by djhoese** [comment]
Thanks! I actually trying to help a user of my software debug a unicode issue on Windows. Noticed the Windows package was missing and was :crossed_fingers: that this was the issue. Doesn't seem like it.

**Comment by xylar** [comment]
The package hasn't built yet.  It's sitting in the queue: https://github.com/conda-forge/proj.4-feedstock/runs/505574965
Even after it builds, it takes about half an hour to be able to install it.  So maybe try again in a few hours?
