### ISSUE TITLE
v7.0.1 does not appear to be on anaconda.org

### ISSUE THREAD

**Issue by synapticarbors** [conda-forge/proj.4-feedstock#84]
I can see that the recipe currently specifies v7.0.1, but there are no corresponding files on anaconda.org:

https://anaconda.org/conda-forge/proj/files

**Comment by beckermr** [comment]
You can always check the ci job on master. In this case it appears that that job never ran. Push an empty commit.

**Comment by xylar** [comment]
We might as well rerender.  Which I'm doing in #85
