### ISSUE TITLE
recipe url is defined as an array

### ISSUE THREAD

**Issue by hobu** [conda-forge/proj.4-feedstock#96]
I believe https://github.com/conda-forge/proj.4-feedstock/blame/master/recipe/meta.yaml#L8 shouldn't have a `-` in front of it. A simple `conda build recipe` fails with the following:

```
  File "/Users/hobu/miniconda3/envs/proj/lib/python3.8/site-packages/conda_build/utils.py", line 1626, in merge_or_update_dict
    base_value = base.get(key, value)
```

**Comment by xylar** [comment]
Odd, I wonder why this hasn't caused a problem before.

**Comment by hobu** [comment]
> Odd, I wonder why this hasn't caused a problem before.

Yeah, something underneath must have changed. What is the proper way to define it?
